# Generated by Django 2.2 on 2019-06-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('customauth', '0002_auto_20190525_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='to_read',
            field=models.ManyToManyField(to='catalog.Book'),
        ),
    ]
