# Generated by Django 2.2.5 on 2019-09-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0003_customuser_to_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='to_read',
            field=models.ManyToManyField(blank=True, to='catalog.Book'),
        ),
    ]
